apache:
  replicaCount: 1
  image:
    repository: midi79/apache
    tag: 2.4
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

wildfly:
  replicaCount: 1
  image:
    repository: midi79/wildfly
    tag: "14.0"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi