apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wildfly
  labels:
    app: {{ .Release.Name }}-wildfly
spec:
  replicas: {{ .Values.wildfly.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wildfly
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wildfly
    spec:
      containers:
      - name: wildfly
        image: "{{ .Values.wildfly.image.repository }}:{{ .Values.wildfly.image.tag }}"
        imagePullPolicy: {{ .Values.wildfly.image.pullPolicy }}
        ports:
        - containerPort: 8080
        - containerPort: 9990
        resources:
          {{- toYaml .Values.wildfly.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10